name: Release to Production

on:
  schedule:
    - cron: '0 2 * * *' # every 2:00 am everyday

jobs:
  build-frontend:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  build-backend:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  run-e2e-cypress-test:
    needs: [build-frontend, build-backend]
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Sprint up frontend & backend
        run: echo Hello, world!

      - name: Run Cypress
        run: echo Hello, world!

  deploy-frontend-to-vercel:
    needs: [run-e2e-cypress-test]
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Heroku!
        run: echo Hello, world!

  deploy-backend-to-heroku:
    needs: [run-e2e-cypress-test]
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Heroku!
        run: echo Hello, world!
